<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'DemoController' => $typo3InstallDir . 'typo3conf/ext/myextension/Classes/Controller/DemoController.php',
);
