base: 'http://vmd159988.contaboserver.net/'
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=258'
languages:
  -
    title: Deutsch
    enabled: true
    locale: de_DE
    hreflang: ''
    base: /
    websiteTitle: ''
    navigationTitle: Deutsch
    flag: de
    languageId: 0
rootPageId: 257
websiteTitle: ''
